name: BorderHoarderEnhanced
version: '${project.version}'
main: com.simondmc.borderhoarder.BorderHoarder
api-version: 1.20.4
authors: [ SimonDMC, bobcodes ]
description: Collect unique items to expand the border!
website: https://simondmc.com

commands:
  startbordergame:
  viewcollecteditems:
  viewmissingitems:
  joinbordergame:
